name: Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-package:
    name: "Test Package"
    runs-on: macos-latest

    steps:
      - uses: ./.github/actions/setup
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Tests
        run: bundle exec rake test:package